# Generated by Django 2.1.2 on 2018-11-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
