# Generated by Django 2.1.2 on 2018-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_auto_20181113_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='fallen',
            field=models.BooleanField(default=False),
        ),
    ]
