# Generated by Django 2.1.3 on 2018-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0008_camera_fallen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loginchk',
            field=models.BooleanField(default=False),
        ),
    ]
